### ISSUE TITLE
Broken Wiki Link

### ISSUE THREAD

**Issue by benfrancis** [openweave/openweave-core#1]
Thanks for releasing this source code!

Just a note to say that the README says "Explore the OpenWeave Wiki on GitHub" but the wiki link is broken.

Is the Weave protocol documented anywhere?

**Comment by benfrancis** [comment]
Aha! https://github.com/openweave/openweave-core/tree/master/doc/specs

**Comment by Vyrastas** [comment]
All documentation will be found at openweave.io going forward.
