### ISSUE TITLE
Commit ae4b0dc32 Breaks TestDNSResolution against 'make check' with LwIP

### ISSUE THREAD

**Issue by gerickson** [openweave/openweave-core#107]
Previously, all DNS testing was disabled when building for LwIP; however, this had the downside of precluding validating changes to DNS functionality.

Because of the way LwIP works, DNS testing for LwIP cannot work without a format test framework like "Happy" or some other manual networking configuration due to its need to talk to a TUN device and to bridge the hosts network interface.

For TestDNSResolution, we should probably:

* **Build:** Always
* **Test:**
-- LwIP, w/o Happy: **No**
-- LwIP, w/ Happy: **Yes** (Need Driver)
-- Sockets, w/o Happy: **Yes**
-- Sockets, w/ Happy: **Yes**

**Comment by gerickson** [comment]
At this point, commit 13c5774b5dcfbc1df79c0bd1ae1c0e4a9798bc4f addresses ensuring the TestWoble is always built but only run when building against BSD sockets. Commit 04364c1993c0399b86dafc285775f17607068538 addresses ensuring basic, non-LwIP-based unit and functional tests are run.

Remaining open is determining how to run TestDNSResolution in an LwIP environment, likely with Happy.

**Comment by gerickson** [comment]
@jenniexie, can this now be closed?

**Comment by jenniexie** [comment]
Yes Grant.
Inet DNS resolution test for both default linux and Lwip are in master, both tests passed.
