### ISSUE TITLE
Add Full IPv4 / IPv6 Multicast Group Join / Leave and Loopback Control Support to Inet

### ISSUE THREAD

**Issue by gerickson** [openweave/openweave-core#115]
Add full IPv4 and IPv6 multicast join / leave and multicast loopback control support to the Inet layer.

**Comment by gerickson** [comment]
At this point, on the branch feature/inet-multicast, BSD sockets support is working with functional tests.

LwIP is coming along, mostly hobbled by the incomplete and buggy IPv6 and multicast support in 2.0.3. I am back porting upstream patches to the 2.0.3 + Weave changes LwIP base in openweave-core.

**Comment by gerickson** [comment]
One of the several outstanding LwIP issues is that there are an unexpectedly insufficient number of MLD groups to support the four group multicast functional tests. While I have configured LwIP for 1 + 4 (solicited node + four application groups) MLD groups, the last application group fails unexpectedly.

This turns out to be the case because in LwIP 2.0.3 the ND protocol implementation is broken. LwIP attempts to perform DAD on an IPv6 any (zero) address resulting in an incorrect solicited node join of FF02::1:FF00:0, pushing that address to the PREFERRED state, in addition to the correct and expected solicited node join of FF02::1:FF01:726D (for the test node).

LwIP 2.1.0 upstream appears to fix this by the complete refactoring and rework of ND6.

**Comment by jaylogue** [comment]
So can we work around the issue in 2.0.3 by over-provisioning the number of groups?

**Comment by gerickson** [comment]
> So can we work around the issue in 2.0.3 by over-provisioning the number of groups?

Yes, I've proven that works around the issue.

**Comment by gerickson** [comment]
With the application of a few select upstream patches:

- 71810d041: ipv6: adjust MLD membership on address state changes
- e0c5e198: nd6: improve address autoconfiguration support
- 2ff04a93: nd6: check link status before sending packets
- d9933457: nd6: fix Duplicate Address Detection
- 22c2fd1b: nd6: improve router selection
- 08de0e96: ip6/nd6: route using on-link prefixes, not addresses
- 0b9d7a38: ip6: improve source address selection

I have LwIp somewhat working for the following configurations:

- UDP over IPv4: 100%
- ICMPv4 over IPv4: 100%
- UDP over IPv6: Partial, incorrectly picks any/unspecified address as source rather than the LLA.
- ICMPv6 over IPv6: Fails, ERR_RTE.

**Comment by gerickson** [comment]
After reviewing RFC 6724 and looking at the behavior of BSD sockets on Linux with the same test cases, it appears correct that IP6_ANY_TYPE address should not be assigned to a network interface and, if they are, should not be considered in IPv6 source address selection.

Consequently, with upstream patch 0b9d7a38 applied, the following fix seems to make both the UDP and ICMPv6 over IPv6 work correctly with the expected LLA used as the source for the site-local multicast (as with Linux / BSD sockets), borrowing the same warning used by the Linux kernel for such cases.

```
    if (ip6_addr_isany(cand_addr) || ip6_addr_ismulticast(cand_addr)) {
        LWIP_DEBUGF(IP6_DEBUG | LWIP_DBG_LEVEL_WARNING, ("unspecified / multicast address assigned as unicast address on %c%c%u\n", netif->name[0], netif->name[1], netif->num));
        continue;
    }
```

**Comment by gerickson** [comment]
https://savannah.nongnu.org/bugs/index.php?55433

**Comment by gerickson** [comment]
At this point LwIP and sockets implementations are 100% complete and the full suite of functional tests are working across both implementations.

**Comment by gerickson** [comment]
Completed and merged.
