### ISSUE TITLE
TestECMath does not report error

### ISSUE THREAD

**Issue by jaylogue** [openweave/openweave-core#139]
While testing some changes that caused EC point operations in TestECMath to fail I discovered that running "make -f Makefile-Standalone check" did not report a failure. This appears to be because the main() function in TestECMath.cpp does not report the failure back to the caller.

(This issue corresponds to WEAV-1881).

**Comment by gerickson** [comment]
https://github.com/openweave/openweave-core/pull/158

**Comment by gerickson** [comment]
Fixed.
