### ISSUE TITLE
Add LwIP-based Network and Service Tests to Continuous Integration Matrix

### ISSUE THREAD

**Issue by gerickson** [openweave/openweave-core#154]
Currently, LwIP-based network and service tests are not included in the continuous integration matrix, leaving a substantial amount of exposure in continuous integration.

**Comment by gerickson** [comment]
https://github.com/openweave/openweave-core/pull/155

**Comment by gerickson** [comment]
Currently, three tests are failing under LwIP:

1. FAIL: happy/tests/standalone/pairing/test_weave_ble_01.py
2. FAIL: happy/tests/standalone/time/test_weave_time_local.sh
3. FAIL: happy/tests/standalone/time/test_weave_time_auto.sh

**Comment by gerickson** [comment]
@jenniexie, any updates or insights on this?

**Comment by jenniexie** [comment]
Hi Grant, I haven't worked on this yet, I should be able to get some time for this one this week.
I will confirm with you for the actions I plan to do tomorrow.

**Comment by jenniexie** [comment]
I am seeing 4 test cases are failing on my setup:
FAIL: happy/tests/standalone/wdmNext/test_weave_wdm_next_mutual_subscribe_48.py
FAIL: happy/tests/standalone/wdmNext/test_weave_wdm_next_mutual_subscribe_61.py
FAIL: happy/tests/standalone/time/test_weave_time_local.sh
FAIL: happy/tests/standalone/time/test_weave_time_auto.sh
And I am not seeing test_weave_ble_01.py in my test result list, maybe it is disabled for LWIP case, I will on these ones and try to fix them.

**Comment by gerickson** [comment]
Resolved.
