### ISSUE TITLE
ObjC++ API: Add support for Rendezvous WiFi ESSID Suffix field

### ISSUE THREAD

**Issue by jaylogue** [openweave/openweave-core#208]
Previously, the OpenWeave Device Description profile was extended to support a Rendezvous WiFi ESSID Suffix field in a Weave Device Descriptor (see issue #142, commit 6fb3782d1).  **This issue is to add support for using the new field from Objective C++, via the existing NLWeaveDeviceDescriptor object.**

The NLWeaveDeviceDescriptor object should be extended in a similar manner as was done for the Java object.  In particular, a new BOOL method should be added which returns the value of the IsRendezvousWiFiESSIDSuffix flag.  The application can then use this to determine whether the existing RendezvousWiFiESSIDSuffix contains the full SSID or just the SSID suffix.

**Comment by robszewczyk** [comment]
Resolved: https://github.com/openweave/openweave-core/pull/214
