### ISSUE TITLE
Building without python causes repeated failures

### ISSUE THREAD

**Issue by jaylogue** [openweave/openweave-core#238]
Later Ubuntu releases do not come with a 'python' executable (i.e. python 2.7) installed by default.  Building OpenWeave on such a system results in a failure while attempting to run the gen-oid-table.py script.  Conveniently, the generated error message properly identifies that the python command was not found.

However, as a result of this failure, the ASN1OID.h file that is checked in as part of the openweave-core source tree is replaced with an empty file.  Subsequently, any attempt to build OpenWeave, even after python 2.7 is installed, fails with the following error:

```
../../src/include/Weave/Support/ASN1.h:123:28: error: 'OID' has not been declared
ASN1_ERROR GetObjectId(OID& oid);
```
This must be corrected by reverting the ASN1OID.h file.

**Comment by gerickson** [comment]
Can we / do we work with any version of Python or do we strictly require Python 2.7?

**Comment by jaylogue** [comment]
Unclear.  But that script is very simple, so I expect the version doesn't matter.

**Comment by gerickson** [comment]
Regardless of the Python version question, it seems like we'll / I'll need to differentiate between the "--{enable,disable}-python" support option (which is mostly about Device Manager and Happy) and just having a Python interpreter.

Having  a Python interpreter will be flat-out required, independent of the "--{enable,disable}-python" option.

I'll take a pass at coding this up.

**Comment by jaylogue** [comment]
It would also be nice to not have a version of ASN1OID.h checked in at all, and to have the make logic generate the script in the build directory, rather than the source directory.

**Comment by gerickson** [comment]
Addressed in https://github.com/openweave/openweave-core/pull/240.

**Comment by gerickson** [comment]
Resolved.
