### ISSUE TITLE
Google group openweave-users is not accessible. 

### ISSUE THREAD

**Issue by tehnorm** [openweave/openweave-core#337]
When trying to access https://groups.google.com/forum/#!forum/openweave-users I get `You do not have permission to access this content. (#418)`

How does one gain access to `openweave-users`?

**Comment by jwhui** [comment]
As mentioned in https://github.com/openthread/openthread/issues/3255#issuecomment-521713936:

> Try signing in and becoming a member of [openweave-users](https://groups.google.com/forum/#!forum/openweave-users) - it is currently configured such that only group members can view posts.

**Comment by Dayna-A** [comment]
Hi @jwhui how to we request access to the openweave-users group?
Searches for the group find no results.
![image](https://user-images.githubusercontent.com/35708093/63112197-7ac62c80-bf44-11e9-9435-a34906a68f3c.png)

**Comment by tehnorm** [comment]
@jwhui thanks for the quick reply. I'm seeing the same as @Dayna-A 

<img width="1260" alt="Screenshot 2019-08-15 11 11 47" src="https://user-images.githubusercontent.com/228909/63112561-bf09fa80-bf4d-11e9-90f6-aa0620a80f5c.png">

**Comment by gerickson** [comment]
Norm,

I’ll take a look into this matter. The last public post was June 15. So, in theory, this has worked in the past. Stay tuned.

Best,

Grant

**Comment by gerickson** [comment]
@tehnorm, we've replicated your findings and have escalated this to the Google Groups team.

**Comment by Dayna-A** [comment]
@gerickson Is there any chance that you guys are able to manually add us to the group in the interim?

**Comment by gerickson** [comment]
@Dayna-A, I'd warmly welcome an opportunity to do so; however, whatever is blocking your access is also blocking my administrator access. I can see all historical posts; however, if I try to administer the group, I likewise get an error.

**Comment by Dayna-A** [comment]
@gerickson Gotcha. Thank you for your help.

**Comment by tehnorm** [comment]
Hi @gerickson and @jwhui - thank you again for looking into this issue. Have we been able to make any progress so far? Thanks again for your help.

**Comment by gerickson** [comment]
@tehnorm, regrettably, no updates as of yet.

**Comment by jaylogue** [comment]
Hi Norm,

Examples of direct device-to-device interaction are limited at this time.
However, in the next few weeks we plan on releasing a new example
application for the nRF52840 specifically designed to demonstrate
device-to-device communication using Weave.  The new example app will
interact with an updated version of the lock example, where it will serve
as a (simulated) sensor for the state of the door.  The pair of devices
will support multiple modes of operation, including one that does not
require the devices to be paired to a service.  (Some of these, of course,
will be example configurations, designed more for illustration than
production use).

In the meantime, I can also point you at the feature/lighting-demo
<https://github.com/openweave/openweave-esp32-demo/tree/feature/lighting-demo>
branch of the openweave-esp32-demo
<https://github.com/openweave/openweave-esp32-demo> repository.  It
contains a working example of devices communicating using Weave Data
Management (WDM) commands for the purposes of lighting control (see
LightSwitch.cpp
<https://github.com/openweave/openweave-esp32-demo/blob/feature/lighting-demo/main/LightSwitch.cpp>
 and LightController.cpp
<https://github.com/openweave/openweave-esp32-demo/blob/feature/lighting-demo/main/LightController.cpp>).
While this code currently targets the ESP32 platform (and WiFi), rather
than the nRF52840, the Weave-specific portions are highly portable.

Comments are regrettably sparse in the feature/lighting-demo code, but feel
free to ping me if you have specific questions.

--Jay

Jay Logue
The OpenWeave Team
jaylogue@google.com

**Comment by Dayna-A** [comment]
Hi @jaylogue, 
Just a few questions with the lighting demo: 
What is the best method to join the two devices to the same network once they are flashed with the demo?
How do they determine control one over another?
Thank you for all of your help!

**Comment by gerickson** [comment]
@Dayna-A and @tehnorm, we believe this issue was caused by https://support.google.com/a/answer/9191148  and we believe we have regained administrative control of the group. Can you please retry / recheck the operations you were attempting before and confirm if the problem still persists?

**Comment by Dayna-A** [comment]
@gerickson Thanks for staying on top of this :-)
Unfortunately I am still seeing the same result.
![image](https://user-images.githubusercontent.com/35708093/65639665-680c3200-df9d-11e9-9a63-84c81b2d251e.png)

**Comment by gerickson** [comment]
@Dayna-A, I flipped another setting. Please make one more try if you are willing.

**Comment by Dayna-A** [comment]
@gerickson I'm in!!
Thanks again for your help with this 👍

**Comment by gerickson** [comment]
@Dayna-A, you're welcome! Thanks for your patience!
