### ISSUE TITLE
Python TLVWriter init bug that prevents re-use

### ISSUE THREAD

**Issue by wijnandatgoogle** [openweave/openweave-core#357]
TLVWriter has in init like so:
def __init__(self, encoding=bytearray(), implicitProfile=None):
That does not lead or re-init of encoding, as you might expect. Instead, encoding should be defaulting to None, and a run-time check for None can then do:
if encoding == None:
   encoding = bytearray()

**Comment by jaylogue** [comment]
Fixed in openweave-core:master in commit 37b3c15.
