### ISSUE TITLE
Support mutli-interface IPv4 broadcast

### ISSUE THREAD

**Issue by jaylogue** [openweave/openweave-core#368]
_Based on further consideration, I am simplifying the goal of this issue in order to better reflect the functionality that I believe application developers will want._

Currently, if one specifies the IPv4 broadcast address (255.255.255.255) as the destination of a UDP Weave message, the choice of interface over which the packet is set is left up to the underlying OS.  Often, this ends up being the host's default interface.  This is undesirable in certain situations, such as on a mobile phone that is connected to the private WiFi network of a device, but has a default route pointing to its cellular interface.

Proposed new behavior: Add logic to the Weave Message Layer SendMessage() code to recognize an attempt to send to the IPv4 local broadcast address (255.255.255.255) and translate this into a series of UDP packet sends directed at each interface that supports broadcast.  For each UDP packet, the destination address will be the  IPv4 local broadcast address.

_**Previous proposed behavior...**_

_... Add logic to the Weave Message Layer SendMessage() code to recognize an attempt to send to the IPv4 broadcast address and translate this into individual, per-interface sends using the appropriate subnet-specific broadcast addresses for each interface.  The Weave Message Layer will handle the work of enumerating interfaces and determining their broadcast addresses.  This has the added benefit of allowing a single SendMessage() call to broadcast across all compatible interfaces._

**Comment by gerickson** [comment]
Is there a way this could be further optimized by having clients provide a "subnet" list (Thread, WiFi, etc.) with the default being "all"?

**Comment by jaylogue** [comment]
@gerickson 

> Is there a way this could be further optimized by having clients provide a "subnet" list (Thread, WiFi, etc.) with the default being "all"?

The context of this issue is IPv4, so Weave IPv6 addressing isn't relevant.  A typically application of this would be a mobile trying to rendezvous with a device using IPv4.

**Comment by jaylogue** [comment]
Fixed in openweave-core:master in commit 9238c86.
