### ISSUE TITLE
UDPEndPoint not setting REUSEADDR on later LwIP versions

### ISSUE THREAD

**Issue by jaylogue** [openweave/openweave-core#383]
A logic bug in UDPEndPoint::GetPCB() results in the SOF_REUSEADDR option not being set on the UDP PCB when the code is built with versions of LwIP later than 1.4.  This in turn causes subsequent failures in the Weave Message Layer when it tries to bind address-specific end points to the Weave port after the general purpose end point has been bound.

**Comment by gerickson** [comment]
Are there specific unit / functional tests that can be added to ensure we don't have regressions in this area in the future?

**Comment by jaylogue** [comment]
Fixed in commit e3daab3f
