### ISSUE TITLE
Error building Standalone Application

### ISSUE THREAD

**Issue by raupune** [openweave/openweave-core#4]
Dear, 
I am referring to instructions given on BUILDING.md page. 

I get error when I try to build Standalone application.

Error Description:
_../../src/include/Weave/Support/crypto/WeaveRNG.h:33:2: error: #error "INVALID WEAVE CONFIG: OpenSSL RNG implementation enabled but OpenSSL not available (WEAVE_CONFIG_RNG_IMPLEMENTATION_OPENSSL == 1 && WEAVE_WITH_OPENSSL == 0)."
 #error "INVALID WEAVE CONFIG: OpenSSL RNG implementation enabled but OpenSSL not available (WEAVE_CONFIG_RNG_IMPLEMENTATION_OPENSSL == 1 && WEAVE_WITH_OPENSSL == 0)."
  ^~~~~_

I am using Ubuntu 18.

Screenshot of error: Please open the link: https://goo.gl/iPzw4e

One more suggestion: OpenWeave TAG on StackOverFlow is not active. No users are actively commenting on it. Please make it active.

**Comment by jaylogue** [comment]
Hi raupune,

Thank you for your interest in OpenWeave.

From the error message you posted, it looks like you don't have the openssl development package installed.  Try installing libssl-dev using the following command:

`sudo apt-get install libssl-dev`

If that doesn't work, it would be useful for us to see the contents of your configure log file.  By default this file is located at build/x86_64-unknown-linux-gnu/config.log within your source directory.  If you can attach this file to the issue we can investigate further.

Regarding establishing an openweave tag on StackOverflow, tags are generally created as people ask questions.  However we will look into expressly requesting the openweave tag to be created.

--Jay

**Comment by raupune** [comment]
Thanks. Issue solved.
