### ISSUE TITLE
BleEndPointPool elements can be misaligned when compiler optimizations are active

### ISSUE THREAD

**Issue by jasongraffius** [openweave/openweave-core#416]
When space optimization is turned on, [`BLEEndPoint`](https://github.com/openweave/openweave-core/blob/master/src/ble/BleLayer.cpp#L103) elements can end up not aligned correctly in the [`BleEndPointPool`](https://github.com/openweave/openweave-core/blob/master/src/ble/BleLayer.cpp#L98). Alignment of both [`PoolElement`](https://github.com/openweave/openweave-core/blob/master/src/ble/BleLayer.cpp#L109)s and [`sEndPointPool`](https://github.com/openweave/openweave-core/blob/master/src/ble/BleLayer.cpp#L111) should be forced into 8-byte alignment.

**Comment by jaylogue** [comment]
Fixed.
