### ISSUE TITLE
How to use in Embedded Platform

### ISSUE THREAD

**Issue by raupune** [openweave/openweave-core#5]
Dear, How to compile Openweave Project for Embedded Platform?

Any tutorial available on this? 

I want to use this library on 32 bit Arm Processor.

How to create library file (.a extension) and use it in Embedded Projects?

**Comment by Vyrastas** [comment]
Hi @raupune, we don't have a detailed guide for that yet, but take a look at this page, it has information on embedded targets and linking:

https://openweave.io/guides/build#embedded
https://openweave.io/guides/build#project_linking

**Comment by Vyrastas** [comment]
Closing stale issue.
