### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by raupune** [openweave/openweave-core#6]
Dear,
I am able to build Standalone Application on Ubuntu Platform.
Even I am about to run./configure command successfully.
But I get an Error when running 'make all' command.
Will you please help me to solve this error.
Giving link to error screenshot below.
https://goo.gl/8uBAUQ

**Comment by raupune** [comment]
Dear  jaylogue ,
Thanks for your prompt reply. 
uuid.c doesn't exists at given location.
But it exists at different location
**./third_party/bluez/repo/lib**

I have cloned full repo from Github.
On Github too it is present at '**./third_party/bluez/repo/lib**' location.

Thanks.

**Comment by robszewczyk** [comment]
Hi raupune,

it looks like I did not correctly re-bootstrapped the bluez package after it got subtreed into the openweave.  I just pushed the change that should fix the build

best regards
