### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by raupune** [openweave/openweave-core#7]
Dear,
I am getting Build Error:
_libtool: Version mismatch error.  This is libtool 2.4.2, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2
libtool: and run autoconf again._

![screenshot from 2018-07-08 20-08-01](https://user-images.githubusercontent.com/25011169/42421369-1051cf7e-82f2-11e8-8418-0f244f9b3806.png)

**Comment by raupune** [comment]
I am using Ubuntu 18. And current libtool bersion is:

libtool --version
libtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by robszewczyk** [comment]
Hi @raupune .  Could you re-run `./bootstrap` prior to running `make -f Makefile-Standalone`?

**Comment by raupune** [comment]
Dear robszewczyk,
Thanks for the prompt reply.
Build errors solved.
Will you please add this instructions in _**BUILDING.md**_ file?

**Comment by Vyrastas** [comment]
I've updated the build instructions on openweave.io:
https://openweave.io/guides/build#standalone_application

Closing.
