### ISSUE TITLE
OW Build Guide Error

### ISSUE THREAD

**Issue by kevin-zhux** [openweave/openweave-core#79]
Dear,

I follow the instructions on 'https://openweave.io/guides/build' Project Linking, after staging, there is not a /include directory under [openweave-output], there are /etc, /lib and /usr instead, could you confirm?

Best Regard,
Kevin Zhu

**Comment by Vyrastas** [comment]
Hi @kevin-zhux, thanks for reporting this.  I ran through the build and it looks like the structure of the output has indeed changed.  I'll update the guide on openweave.io.

Public headers are now at <openweave-output>/usr/local/include
Libraries are now at <openweave-output>/usr/local/lib

**Comment by Vyrastas** [comment]
https://openweave.io/guides/build#project_linking has been updated the proper paths.

Closing as resolved.
