### ISSUE TITLE
make all fails

### ISSUE THREAD

**Issue by raupune** [openweave/openweave-core#8]
Dear,
Getting error when I am running **_make all_** command.
Also **_bin/_** and **_lib/_** folders are not generated.
**_lib/_** contains Architecture-independent libraries. Does this means I can use these libraries for Embedded Arm Platform?

![screenshot from 2018-07-10 22-30-00](https://user-images.githubusercontent.com/25011169/42525455-d4fcfe1c-8490-11e8-9100-3541a42784e7.png)

**Comment by Vyrastas** [comment]
Hi @raupune, not sure if you've solved this yet or not, but make sure you have the Perl Text::Template module installed as detailed here: https://openweave.io/guides/build#packages

**Comment by Vyrastas** [comment]
Closing stale issue.
